#!/usr/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ "$1" == "run" ]]; then
    cd engine
    maturin develop
    cd ../server
    python3 main.py
fi

if [[ "$1" == "devbuild" ]]; then
    cd engine
    maturin develop
fi