name: "type checking"
on:
  push:
  pull_request:

jobs:
  check:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: "3.12"
            cache: "pip"
      - name: "Installing dependencies"
        run: "pip install -r requirements.txt"
      - name: "Inspecting"
        run: "basedpyright"
